'use client'

import Head from "next/head";
// import styles from "./styles/Home.module.css"
import styles from "@/styles/Home.module.css"
import Header from "@/components/Header";
import HeroSection from "@/components/Herosection";
import SearchComp from "@/components/SearchResults";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Etherscan Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
      <ToastContainer />
        <Header />
        <SearchComp />
        <HeroSection />
      </section>
    </>
  );
}